CREATE DATABASE library;
SET search_path TO library;

CREATE TABLE books
(
    id            INT GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR,
    author        VARCHAR,
    genre         VARCHAR,
    publisment_id INT
);

CREATE TABLE publisment
(
    id       INT GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR,
    address  VARCHAR,
    contacts VARCHAR
);

CREATE TABLE book_existed
(
    book_id     INT,
    existed     BOOLEAN,
    count       INT,
    date_update TIMESTAMP
);

ALTER TABLE books
    ADD CONSTRAINT books_pk PRIMARY KEY (id);
ALTER TABLE books
    ADD CONSTRAINT publisment_fk FOREIGN KEY (publisment_id) REFERENCES publisment (id) ON DELETE SET NULL;
ALTER TABLE publisment
    ADD CONSTRAINT publisment_pk PRIMARY KEY (id);
ALTER TABLE book_existed
    ADD CONSTRAINT book_fk FOREIGN KEY (book_id) REFERENCES books (id);

INSERT INTO books (name, author, genre)
VALUES ('Вільям Вілсон', 'Річард Лейн', 'Детектив'),
       ('Війна і мир', 'Лев Толстой', 'Роман'),
       ('Ідіот', 'Федір Достоєвський', 'Роман'),
       ('Мертві душі', 'Микола Гоголь', 'Поема'),
       ('Місто Гріхів', 'Маріо Пьюзо', 'Детектив'),
       ('Місто Скляних Турець', 'Орхан Памук', 'Роман'),
       ('Місто Сонця', 'Томас Мур', 'Фентезі'),
       ('Кладовище домашніх тварин', 'Стівен Кінг', 'Жахи'),
       ('Воно', 'Джон Берні', 'Жахи'),
       ('Керрі', 'Джон Берні', 'Фентезі'),
       ('Квартира на двох', 'Джон Берні', 'Фентезі'),
       ('Портрет Доріана Грея', 'Джон Берні', 'Фентезі'),
       ('Парфуми', 'Джон Берні', 'Фентезі'),
       ('Необхідні речі', 'Джон Берні', 'Фентезі'),
       ('Чотири після опівночі', 'Джон Берні', 'Фентезі'),
       ('Корпорація кидайте курити', 'Джон Берні', 'Фентезі');


INSERT INTO publisment (name, address, contacts)
VALUES ('Folio', 'Kiev', '096-451-54-76'),
       ('KSD', 'Lyviv', '097-876-56-76'),
       ('Vivat', 'Odessa', '050-765-54-34'),
       ('Jio', 'Termopil', '098-760-54-12'),
       ('Judas', 'Kiev', '097-786-23-23'),
       ('Folio2', 'Kiev', '096-451-54-76'),
       ('KSD2', 'Lyviv', '097-876-56-76'),
       ('Vivat2', 'Odessa', '050-765-54-34'),
       ('Jio2', 'Termopil', '098-760-54-12'),
       ('Judas2', 'Kiev', '097-786-23-23');

INSERT INTO book_existed (book_id, existed, count, date_update)
VALUES (1, TRUE, 2, '2021-01-01'),
       (2, TRUE, 3, '2021-01-12'),
       (3, TRUE, 4, '2022-03-01'),
       (4, TRUE, 5, '2021-08-01'),
       (5, FALSE, 0, '2021-01-01'),
       (6, TRUE, 7, '2021-01-01'),
       (7, TRUE, 8, '2021-01-01'),
       (8, TRUE, 9, '2021-01-01'),
       (9, TRUE, 10, '2021-01-01'),
       (10, TRUE, 11, '2021-01-01'),
       (11, TRUE, 12, '2021-01-01'),
       (12, FALSE, 0, '2021-01-01'),
       (13, TRUE, 14, '2021-01-01'),
       (14, TRUE, 15, '2021-01-01'),
       (15, TRUE, 16, '2021-01-01');



SELECT *
  FROM books
 WHERE author = 'Лев Толстой'
   AND genre = 'Роман'
 ORDER BY id, name, author, genre;

SELECT *
  FROM publisment
 WHERE address = 'Kiev'
 ORDER BY name, address, contacts;

SELECT *
  FROM book_existed
 WHERE existed = TRUE
   AND count = 2
   AND date_update = TO_DATE('2021-01-01', 'YYYY-MM-DD')
 ORDER BY existed, count, date_update;

UPDATE book_existed
   SET count = (SELECT count
                  FROM book_existed
                 WHERE book_id = 3) + 1
 WHERE book_id = 3;

SELECT b.genre, COUNT(b.genre) AS count
  FROM books b
           JOIN book_existed be ON b.id = be.book_id
 WHERE be.existed = TRUE
 GROUP BY b.genre
 ORDER BY genre;

SELECT p.address, b.name AS name
  FROM publisment p
           JOIN books b ON p.id = b.publisment_id
           JOIN book_existed be ON b.id = be.book_id
 WHERE be.existed = TRUE
 GROUP BY p.address, b.name, b.author
 ORDER BY p.address;

SELECT b.author, p.name, COUNT(p.id) AS count
  FROM books b
           JOIN publisment p ON b.publisment_id = p.id
 GROUP BY b.author, p.name
 ORDER BY b.author, count;

UPDATE book_existed SET count = 0 WHERE existed = FALSE;

DELETE
  FROM books
 WHERE publisment_id IN (SELECT id FROM publisment WHERE address = 'Odessa');

DELETE FROM publisment WHERE id = 2;
DELETE FROM book_existed WHERE book_id = 2;

